"""tenant_roles.can_activate_config - the risk_manager-equivalent capability flag.

A third elevatable flag alongside can_admin_tenant/can_reveal_pii: may propose or
confirm a configuration activation (BR-715 maker-checker), without needing full
tenant admin. config_service.maker_checker.ensure_eligible() now checks this
dynamically for both fixed and custom roles, via cp_common.dynamic_roles.

Revision ID: 034ddfa06f53
Revises: 12cc3061cd30
Create Date: 2026-08-17 11:22:09.793796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034ddfa06f53'
down_revision: Union[str, None] = '12cc3061cd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_roles', sa.Column('can_activate_config', sa.Boolean(), server_default='false', nullable=False), schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_roles', 'can_activate_config', schema='tenant')
    # ### end Alembic commands ###
