"""schema per service

Moves every table out of `public` into a schema owned by the service responsible for it.
Nothing about the data changes: ALTER TABLE ... SET SCHEMA is a catalogue update, so
indexes, constraints and contents move with the table and no rows are rewritten.

Written by hand rather than autogenerated. Alembic sees a relocation as "drop fourteen
tables and create fourteen identical ones" - a correct diff and a catastrophic migration.

Revision ID: 110f2828d64b
Revises: 7737ff6043ff
Create Date: 2026-07-29 15:41:17.917148

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '110f2828d64b'
down_revision: Union[str, None] = '7737ff6043ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# table -> owning schema
MOVES = {
    "audit_logs": "platform",
    "config_generation": "platform",
    "tenants": "tenant",
    "tenant_users": "tenant",
    "platform_users": "tenant",
    "branding": "branding",
    "tenant_configs": "config",
    "fact_transaction": "analytics",
    "fact_alert": "analytics",
    "fact_case": "analytics",
    "saved_views": "analytics",
    "report_subscriptions": "analytics",
    "case_documents": "cases",
    "case_transitions": "cases",
}

SCHEMAS = ("platform", "tenant", "branding", "config", "analytics", "cases")


def upgrade() -> None:
    for schema in SCHEMAS:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
    for table, schema in MOVES.items():
        # Guarded so the migration is re-runnable against a partially moved database.
        op.execute(
            "DO $$ BEGIN "
            "IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' "
            f"AND tablename = '{table}') THEN "
            f'ALTER TABLE public."{table}" SET SCHEMA "{schema}"; '
            "END IF; END $$;")


def downgrade() -> None:
    for table, schema in MOVES.items():
        op.execute(
            "DO $$ BEGIN "
            f"IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = '{schema}' "
            f"AND tablename = '{table}') THEN "
            f'ALTER TABLE "{schema}"."{table}" SET SCHEMA public; '
            "END IF; END $$;")
    for schema in SCHEMAS:
        op.execute(f'DROP SCHEMA IF EXISTS "{schema}" RESTRICT')
