"""BR-113 (phase 2b): staged elevation on tenant_roles.

Adds pending_change/proposed_by - a can_admin_tenant/can_reveal_pii grant is staged
here until a different eligible actor confirms it (roles.confirm_elevation). A change
that only lowers those flags applies immediately and never touches these columns.

Revision ID: 12cc3061cd30
Revises: 1504d25017bc
Create Date: 2026-08-16 12:21:24.856336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12cc3061cd30'
down_revision: Union[str, None] = '1504d25017bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_roles', sa.Column('pending_change', sa.JSON(), nullable=True), schema='tenant')
    op.add_column('tenant_roles', sa.Column('proposed_by', sa.String(length=255), nullable=True), schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_roles', 'proposed_by', schema='tenant')
    op.drop_column('tenant_roles', 'pending_change', schema='tenant')
    # ### end Alembic commands ###
