"""saved view role audience

Revision ID: 14a6e56ff686
Revises: 816c073c1073
Create Date: 2026-07-29 14:42:08.018043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a6e56ff686'
down_revision: Union[str, None] = '816c073c1073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Empty means "everyone in the tenant", so the server_default backfills every
    # existing shared view to exactly the audience it already had. Narrowing is opt-in;
    # no one loses access to a view they can see today.
    op.add_column('saved_views', sa.Column('shared_roles', sa.String(length=512),
                                           server_default='', nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_views', 'shared_roles')
    # ### end Alembic commands ###
