"""BR-113 (phase 2a): tenant_roles - a tenant's own materialised role catalogue.

Seeded per tenant from cp_common.rbac's fixed catalogue at onboarding
(services/tenant_service/app/roles.py). Read by BR-112's role-catalogue viewer in
preference to the hardcoded catalogue when a tenant has rows. Not yet consulted by
any authorisation check - see the model docstring on TenantRole.

Revision ID: 1504d25017bc
Revises: a7e2c9f14b83
Create Date: 2026-08-16 11:59:46.647224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1504d25017bc'
down_revision: Union[str, None] = 'a7e2c9f14b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('modules', sa.JSON(), nullable=False),
    sa.Column('dashboards', sa.JSON(), nullable=False),
    sa.Column('can_admin_tenant', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_reveal_pii', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.String(length=16), server_default='seeded', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_role_name'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_tenant_roles_tenant_id'), 'tenant_roles', ['tenant_id'], unique=False, schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_tenant_roles_tenant_id'), table_name='tenant_roles', schema='tenant')
    op.drop_table('tenant_roles', schema='tenant')
    # ### end Alembic commands ###
