"""account_ring_score - AI/ML roadmap Phase 3 (HLD AD-15)

Revision ID: 25bc2fecde48
Revises: 1eeb6f553d3e
Create Date: 2026-09-28 13:32:24.871026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bc2fecde48'
down_revision: Union[str, None] = '1eeb6f553d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_ring_score',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('account', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'account'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_account_ring_score_computed_at'), 'account_ring_score', ['computed_at'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_account_ring_score_computed_at'), table_name='account_ring_score', schema='analytics')
    op.drop_table('account_ring_score', schema='analytics')
    # ### end Alembic commands ###
