"""decision score and severity

Revision ID: 293f67391b64
Revises: 6a0f166399b8
Create Date: 2026-08-05 12:12:11.605399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '293f67391b64'
down_revision: Union[str, None] = '6a0f166399b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_log', sa.Column('score', sa.Float(), server_default='0', nullable=False), schema='decision')
    op.add_column('decision_log', sa.Column('severity', sa.String(length=12), server_default='low', nullable=False), schema='decision')
    op.create_index(op.f('ix_decision_decision_log_severity'), 'decision_log', ['severity'], unique=False, schema='decision')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_decision_log_severity'), table_name='decision_log', schema='decision')
    op.drop_column('decision_log', 'severity', schema='decision')
    op.drop_column('decision_log', 'score', schema='decision')
    # ### end Alembic commands ###
