"""staff accountability examination (BR-414)

Revision ID: 3846bf1545f3
Revises: 62fcced6c518
Create Date: 2026-08-03 10:00:32.555046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3846bf1545f3'
down_revision: Union[str, None] = '62fcced6c518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountability_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('examination_id', sa.String(length=36), nullable=False),
    sa.Column('staff_ref', sa.String(length=64), nullable=False),
    sa.Column('staff_name', sa.String(length=255), nullable=False),
    sa.Column('role_at_time', sa.String(length=120), server_default='', nullable=False),
    sa.Column('branch', sa.String(length=120), server_default='', nullable=False),
    sa.Column('finding', sa.String(length=24), nullable=False),
    sa.Column('action_taken', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('recorded_by', sa.String(length=255), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cases'
    )
    op.create_index('ix_accountability_finding_exam', 'accountability_findings', ['tenant_id', 'examination_id'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_accountability_findings_case_id'), 'accountability_findings', ['case_id'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_accountability_findings_examination_id'), 'accountability_findings', ['examination_id'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_accountability_findings_finding'), 'accountability_findings', ['finding'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_accountability_findings_tenant_id'), 'accountability_findings', ['tenant_id'], unique=False, schema='cases')
    op.create_table('staff_accountability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_by', sa.String(length=255), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('examiner', sa.String(length=255), server_default='', nullable=False),
    sa.Column('conclusion', sa.Text(), server_default='', nullable=False),
    sa.Column('systemic_lapse', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('systemic_note', sa.Text(), server_default='', nullable=False),
    sa.Column('concluded_by', sa.String(length=255), server_default='', nullable=False),
    sa.Column('concluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('breached_policy', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('breach_days_allowed', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'case_id', name='uq_accountability_case'),
    schema='cases'
    )
    op.create_index('ix_accountability_tenant_status', 'staff_accountability', ['tenant_id', 'status'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_staff_accountability_case_id'), 'staff_accountability', ['case_id'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_staff_accountability_status'), 'staff_accountability', ['status'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_staff_accountability_tenant_id'), 'staff_accountability', ['tenant_id'], unique=False, schema='cases')
    op.add_column('fact_case', sa.Column('accountability_due_ts', sa.DateTime(timezone=True), nullable=True), schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact_case', 'accountability_due_ts', schema='analytics')
    op.drop_index(op.f('ix_cases_staff_accountability_tenant_id'), table_name='staff_accountability', schema='cases')
    op.drop_index(op.f('ix_cases_staff_accountability_status'), table_name='staff_accountability', schema='cases')
    op.drop_index(op.f('ix_cases_staff_accountability_case_id'), table_name='staff_accountability', schema='cases')
    op.drop_index('ix_accountability_tenant_status', table_name='staff_accountability', schema='cases')
    op.drop_table('staff_accountability', schema='cases')
    op.drop_index(op.f('ix_cases_accountability_findings_tenant_id'), table_name='accountability_findings', schema='cases')
    op.drop_index(op.f('ix_cases_accountability_findings_finding'), table_name='accountability_findings', schema='cases')
    op.drop_index(op.f('ix_cases_accountability_findings_examination_id'), table_name='accountability_findings', schema='cases')
    op.drop_index(op.f('ix_cases_accountability_findings_case_id'), table_name='accountability_findings', schema='cases')
    op.drop_index('ix_accountability_finding_exam', table_name='accountability_findings', schema='cases')
    op.drop_table('accountability_findings', schema='cases')
    # ### end Alembic commands ###
