"""tenant reference data (sanctions, CERSAI)

Revision ID: 4170c1d10273
Revises: 5db111084798
Create Date: 2026-08-03 14:23:37.276447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4170c1d10273'
down_revision: Union[str, None] = '5db111084798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('list_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('match_key', sa.String(length=300), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_reference_entries_list_id'), 'reference_entries', ['list_id'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_reference_entries_tenant_id'), 'reference_entries', ['tenant_id'], unique=False, schema='analytics')
    op.create_index('ix_refentry_list_key', 'reference_entries', ['list_id', 'match_key'], unique=False, schema='analytics')
    op.create_index('ix_refentry_tenant', 'reference_entries', ['tenant_id', 'kind'], unique=False, schema='analytics')
    op.create_table('reference_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=200), server_default='', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), server_default='', nullable=False),
    sa.Column('loaded_by', sa.String(length=255), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'kind', 'version', name='uq_reflist_version'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_reference_lists_kind'), 'reference_lists', ['kind'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_reference_lists_tenant_id'), 'reference_lists', ['tenant_id'], unique=False, schema='analytics')
    op.create_index('ix_reflist_active', 'reference_lists', ['tenant_id', 'kind', 'active'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reflist_active', table_name='reference_lists', schema='analytics')
    op.drop_index(op.f('ix_analytics_reference_lists_tenant_id'), table_name='reference_lists', schema='analytics')
    op.drop_index(op.f('ix_analytics_reference_lists_kind'), table_name='reference_lists', schema='analytics')
    op.drop_table('reference_lists', schema='analytics')
    op.drop_index('ix_refentry_tenant', table_name='reference_entries', schema='analytics')
    op.drop_index('ix_refentry_list_key', table_name='reference_entries', schema='analytics')
    op.drop_index(op.f('ix_analytics_reference_entries_tenant_id'), table_name='reference_entries', schema='analytics')
    op.drop_index(op.f('ix_analytics_reference_entries_list_id'), table_name='reference_entries', schema='analytics')
    op.drop_table('reference_entries', schema='analytics')
    # ### end Alembic commands ###
