"""scheduled reference sources (BR-212)

Revision ID: 4394236cc718
Revises: ca624b9a4a07
Create Date: 2026-08-04 09:37:08.470357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4394236cc718'
down_revision: Union[str, None] = 'ca624b9a4a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('fmt', sa.String(length=8), server_default='lines', nullable=False),
    sa.Column('auth_header', sa.String(length=64), server_default='', nullable=False),
    # The application type seals this column; the database only needs TEXT.
    # Autogenerate renders EncryptedSecret here, which is unimportable in a
    # migration and missing its required argument - the same defect as the
    # mfa_secret migration.
    sa.Column('auth_value', sa.Text(), server_default='', nullable=False),
    sa.Column('key_field', sa.String(length=64), server_default='', nullable=False),
    sa.Column('cadence_hours', sa.Integer(), nullable=False),
    sa.Column('max_shrink', sa.Float(), server_default='0.10', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checksum', sa.String(length=64), server_default='', nullable=False),
    sa.Column('last_entry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), server_default='', nullable=False),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'kind', name='uq_reference_source_kind'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_reference_sources_kind'), 'reference_sources', ['kind'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_reference_sources_tenant_id'), 'reference_sources', ['tenant_id'], unique=False, schema='analytics')
    op.create_index('ix_reference_source_due', 'reference_sources', ['enabled', 'next_due_at'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reference_source_due', table_name='reference_sources', schema='analytics')
    op.drop_index(op.f('ix_analytics_reference_sources_tenant_id'), table_name='reference_sources', schema='analytics')
    op.drop_index(op.f('ix_analytics_reference_sources_kind'), table_name='reference_sources', schema='analytics')
    op.drop_table('reference_sources', schema='analytics')
    # ### end Alembic commands ###
