"""saved views

Revision ID: 4d2eb9625d28
Revises: f7e764173845
Create Date: 2026-07-29 11:14:56.655828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2eb9625d28'
down_revision: Union[str, None] = 'f7e764173845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_views',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dashboard', sa.String(length=32), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('shared', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'owner', 'name', name='uq_saved_view_name')
    )
    op.create_index('ix_saved_view_tenant_owner', 'saved_views', ['tenant_id', 'owner'], unique=False)
    op.create_index(op.f('ix_saved_views_owner'), 'saved_views', ['owner'], unique=False)
    op.create_index(op.f('ix_saved_views_tenant_id'), 'saved_views', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_views_tenant_id'), table_name='saved_views')
    op.drop_index(op.f('ix_saved_views_owner'), table_name='saved_views')
    op.drop_index('ix_saved_view_tenant_owner', table_name='saved_views')
    op.drop_table('saved_views')
    # ### end Alembic commands ###
