"""LEA referral and recovery (BR-415)

Revision ID: 5db111084798
Revises: c986942e0dc4
Create Date: 2026-08-03 14:02:02.013961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db111084798'
down_revision: Union[str, None] = 'c986942e0dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lea_referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('agency', sa.String(length=24), nullable=False),
    sa.Column('agency_office', sa.String(length=200), server_default='', nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('complaint_ref', sa.String(length=120), server_default='', nullable=False),
    sa.Column('fir_number', sa.String(length=120), server_default='', nullable=False),
    sa.Column('referred_on', sa.Date(), nullable=False),
    sa.Column('fir_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.Text(), server_default='', nullable=False),
    sa.Column('referred_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'case_id', name='uq_lea_referral_case'),
    schema='cases'
    )
    op.create_index(op.f('ix_cases_lea_referrals_case_id'), 'lea_referrals', ['case_id'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_lea_referrals_state'), 'lea_referrals', ['state'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_lea_referrals_tenant_id'), 'lea_referrals', ['tenant_id'], unique=False, schema='cases')
    op.create_index('ix_lea_referral_tenant_state', 'lea_referrals', ['tenant_id', 'state'], unique=False, schema='cases')
    op.create_table('recovery_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=200), server_default='', nullable=False),
    sa.Column('recovered_on', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('recorded_by', sa.String(length=255), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cases'
    )
    op.create_index(op.f('ix_cases_recovery_entries_case_id'), 'recovery_entries', ['case_id'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_recovery_entries_mode'), 'recovery_entries', ['mode'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_recovery_entries_tenant_id'), 'recovery_entries', ['tenant_id'], unique=False, schema='cases')
    op.create_index('ix_recovery_tenant_case', 'recovery_entries', ['tenant_id', 'case_id'], unique=False, schema='cases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recovery_tenant_case', table_name='recovery_entries', schema='cases')
    op.drop_index(op.f('ix_cases_recovery_entries_tenant_id'), table_name='recovery_entries', schema='cases')
    op.drop_index(op.f('ix_cases_recovery_entries_mode'), table_name='recovery_entries', schema='cases')
    op.drop_index(op.f('ix_cases_recovery_entries_case_id'), table_name='recovery_entries', schema='cases')
    op.drop_table('recovery_entries', schema='cases')
    op.drop_index('ix_lea_referral_tenant_state', table_name='lea_referrals', schema='cases')
    op.drop_index(op.f('ix_cases_lea_referrals_tenant_id'), table_name='lea_referrals', schema='cases')
    op.drop_index(op.f('ix_cases_lea_referrals_state'), table_name='lea_referrals', schema='cases')
    op.drop_index(op.f('ix_cases_lea_referrals_case_id'), table_name='lea_referrals', schema='cases')
    op.drop_table('lea_referrals', schema='cases')
    # ### end Alembic commands ###
