"""regulatory filings

Revision ID: 62fcced6c518
Revises: 64dc126ce81a
Create Date: 2026-08-02 23:21:12.211548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fcced6c518'
down_revision: Union[str, None] = '64dc126ce81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_filings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=14), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.String(length=255), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.String(length=255), server_default='', nullable=False),
    sa.Column('reference_number', sa.String(length=120), server_default='', nullable=False),
    sa.Column('ack_note', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cases'
    )
    op.create_index(op.f('ix_cases_regulatory_filings_case_id'), 'regulatory_filings', ['case_id'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_regulatory_filings_content_hash'), 'regulatory_filings', ['content_hash'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_regulatory_filings_status'), 'regulatory_filings', ['status'], unique=False, schema='cases')
    op.create_index(op.f('ix_cases_regulatory_filings_tenant_id'), 'regulatory_filings', ['tenant_id'], unique=False, schema='cases')
    op.create_index('ix_filing_case', 'regulatory_filings', ['tenant_id', 'case_id', 'kind', 'generated_at'], unique=False, schema='cases')
    op.create_index('ix_filing_status', 'regulatory_filings', ['tenant_id', 'status'], unique=False, schema='cases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_filing_status', table_name='regulatory_filings', schema='cases')
    op.drop_index('ix_filing_case', table_name='regulatory_filings', schema='cases')
    op.drop_index(op.f('ix_cases_regulatory_filings_tenant_id'), table_name='regulatory_filings', schema='cases')
    op.drop_index(op.f('ix_cases_regulatory_filings_status'), table_name='regulatory_filings', schema='cases')
    op.drop_index(op.f('ix_cases_regulatory_filings_content_hash'), table_name='regulatory_filings', schema='cases')
    op.drop_index(op.f('ix_cases_regulatory_filings_case_id'), table_name='regulatory_filings', schema='cases')
    op.drop_table('regulatory_filings', schema='cases')
    # ### end Alembic commands ###
