"""notifications

Revision ID: 64dc126ce81a
Revises: 6582fbca0c49
Create Date: 2026-08-02 22:12:01.923403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64dc126ce81a'
down_revision: Union[str, None] = '6582fbca0c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The notification service owns this schema; nothing else may write it.
    op.execute('CREATE SCHEMA IF NOT EXISTS "notify"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('min_severity', sa.String(length=10), server_default='warn', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel', name='uq_channel_per_tenant'),
    schema='notify'
    )
    op.create_index(op.f('ix_notify_channel_config_tenant_id'), 'channel_config', ['tenant_id'], unique=False, schema='notify')
    op.create_table('deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), server_default='', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='notify'
    )
    op.create_index('ix_delivery_pending', 'deliveries', ['status', 'next_attempt_at'], unique=False, schema='notify')
    op.create_index(op.f('ix_notify_deliveries_notification_id'), 'deliveries', ['notification_id'], unique=False, schema='notify')
    op.create_index(op.f('ix_notify_deliveries_status'), 'deliveries', ['status'], unique=False, schema='notify')
    op.create_index(op.f('ix_notify_deliveries_tenant_id'), 'deliveries', ['tenant_id'], unique=False, schema='notify')
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('link', sa.String(length=255), server_default='', nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'recipient', 'dedupe_key', name='uq_notify_dedupe'),
    schema='notify'
    )
    op.create_index('ix_notify_inbox', 'notifications', ['tenant_id', 'recipient', 'read_at', 'created_at'], unique=False, schema='notify')
    op.create_index(op.f('ix_notify_notifications_created_at'), 'notifications', ['created_at'], unique=False, schema='notify')
    op.create_index(op.f('ix_notify_notifications_kind'), 'notifications', ['kind'], unique=False, schema='notify')
    op.create_index(op.f('ix_notify_notifications_recipient'), 'notifications', ['recipient'], unique=False, schema='notify')
    op.create_index(op.f('ix_notify_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False, schema='notify')
    op.create_table('preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('muted_kinds', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'recipient', name='uq_pref_recipient'),
    schema='notify'
    )
    op.create_index(op.f('ix_notify_preferences_recipient'), 'preferences', ['recipient'], unique=False, schema='notify')
    op.create_index(op.f('ix_notify_preferences_tenant_id'), 'preferences', ['tenant_id'], unique=False, schema='notify')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notify_preferences_tenant_id'), table_name='preferences', schema='notify')
    op.drop_index(op.f('ix_notify_preferences_recipient'), table_name='preferences', schema='notify')
    op.drop_table('preferences', schema='notify')
    op.drop_index(op.f('ix_notify_notifications_tenant_id'), table_name='notifications', schema='notify')
    op.drop_index(op.f('ix_notify_notifications_recipient'), table_name='notifications', schema='notify')
    op.drop_index(op.f('ix_notify_notifications_kind'), table_name='notifications', schema='notify')
    op.drop_index(op.f('ix_notify_notifications_created_at'), table_name='notifications', schema='notify')
    op.drop_index('ix_notify_inbox', table_name='notifications', schema='notify')
    op.drop_table('notifications', schema='notify')
    op.drop_index(op.f('ix_notify_deliveries_tenant_id'), table_name='deliveries', schema='notify')
    op.drop_index(op.f('ix_notify_deliveries_status'), table_name='deliveries', schema='notify')
    op.drop_index(op.f('ix_notify_deliveries_notification_id'), table_name='deliveries', schema='notify')
    op.drop_index('ix_delivery_pending', table_name='deliveries', schema='notify')
    op.drop_table('deliveries', schema='notify')
    op.drop_index(op.f('ix_notify_channel_config_tenant_id'), table_name='channel_config', schema='notify')
    op.drop_table('channel_config', schema='notify')
    # ### end Alembic commands ###
    op.execute('DROP SCHEMA IF EXISTS "notify" RESTRICT')
