"""per tenant identity providers

Revision ID: 6582fbca0c49
Revises: 8f5e44aba95b
Create Date: 2026-08-02 16:20:33.099381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6582fbca0c49'
down_revision: Union[str, None] = '8f5e44aba95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('protocol', sa.String(length=10), server_default='oidc', nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.Text(), server_default='', nullable=False),
    sa.Column('discovery_url', sa.String(length=255), server_default='', nullable=False),
    sa.Column('authorize_url', sa.String(length=255), server_default='', nullable=False),
    sa.Column('token_url', sa.String(length=255), server_default='', nullable=False),
    sa.Column('jwks_url', sa.String(length=255), server_default='', nullable=False),
    sa.Column('scopes', sa.String(length=255), server_default='openid email profile', nullable=False),
    sa.Column('email_claim', sa.String(length=64), server_default='email', nullable=False),
    sa.Column('groups_claim', sa.String(length=64), server_default='groups', nullable=False),
    sa.Column('role_mapping', sa.JSON(), nullable=False),
    sa.Column('default_role', sa.String(length=32), server_default='analyst', nullable=False),
    sa.Column('jit_provisioning', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_idp_slug'),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_identity_providers_tenant_id'), 'identity_providers', ['tenant_id'], unique=False, schema='tenant')
    op.create_table('sso_login_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('redirect_uri', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('state'),
    schema='tenant'
    )
    op.create_index('ix_sso_state_expiry', 'sso_login_states', ['expires_at'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_sso_login_states_provider_id'), 'sso_login_states', ['provider_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_sso_login_states_tenant_id'), 'sso_login_states', ['tenant_id'], unique=False, schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_sso_login_states_tenant_id'), table_name='sso_login_states', schema='tenant')
    op.drop_index(op.f('ix_tenant_sso_login_states_provider_id'), table_name='sso_login_states', schema='tenant')
    op.drop_index('ix_sso_state_expiry', table_name='sso_login_states', schema='tenant')
    op.drop_table('sso_login_states', schema='tenant')
    op.drop_index(op.f('ix_tenant_identity_providers_tenant_id'), table_name='identity_providers', schema='tenant')
    op.drop_table('identity_providers', schema='tenant')
    # ### end Alembic commands ###
