"""service credentials for machine callers

Revision ID: 6a0f166399b8
Revises: c8b41d0e97aa
Create Date: 2026-08-05 10:27:04.765435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a0f166399b8'
down_revision: Union[str, None] = 'c8b41d0e97aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('secret_hash', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('ip_allowlist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    # EncryptedSecret is a TypeDecorator over text; autogenerate renders it as an
    # unimportable Python type without its argument. The column is plain text - the
    # sealing happens in the application, which is the point of application-layer
    # encryption. This is the third time autogenerate has done this; it is a known
    # trap, not a surprise.
    sa.Column('cert_thumbprint', sa.Text(), server_default='', nullable=False),
    sa.Column('cert_source', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_from', sa.String(length=36), server_default='', nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_reason', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', name='uq_service_credential_client_id'),
    schema='tenant'
    )
    op.create_index('ix_service_credential_tenant', 'service_credentials', ['tenant_id', 'status'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_service_credentials_client_id'), 'service_credentials', ['client_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_service_credentials_status'), 'service_credentials', ['status'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_service_credentials_tenant_id'), 'service_credentials', ['tenant_id'], unique=False, schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_service_credentials_tenant_id'), table_name='service_credentials', schema='tenant')
    op.drop_index(op.f('ix_tenant_service_credentials_status'), table_name='service_credentials', schema='tenant')
    op.drop_index(op.f('ix_tenant_service_credentials_client_id'), table_name='service_credentials', schema='tenant')
    op.drop_index('ix_service_credential_tenant', table_name='service_credentials', schema='tenant')
    op.drop_table('service_credentials', schema='tenant')
    # ### end Alembic commands ###
