"""per-tenant usage metering (BR-110)

Revision ID: 7dfd2035ef75
Revises: 4394236cc718
Create Date: 2026-08-04 10:14:10.428441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfd2035ef75'
down_revision: Union[str, None] = '4394236cc718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_daily',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('meter', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('finalised', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'day', 'meter', name='uq_usage_daily'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_usage_daily_day'), 'usage_daily', ['day'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_usage_daily_meter'), 'usage_daily', ['meter'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_usage_daily_tenant_id'), 'usage_daily', ['tenant_id'], unique=False, schema='analytics')
    op.create_index('ix_usage_tenant_day', 'usage_daily', ['tenant_id', 'day'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_tenant_day', table_name='usage_daily', schema='analytics')
    op.drop_index(op.f('ix_analytics_usage_daily_tenant_id'), table_name='usage_daily', schema='analytics')
    op.drop_index(op.f('ix_analytics_usage_daily_meter'), table_name='usage_daily', schema='analytics')
    op.drop_index(op.f('ix_analytics_usage_daily_day'), table_name='usage_daily', schema='analytics')
    op.drop_table('usage_daily', schema='analytics')
    # ### end Alembic commands ###
