"""report subscriptions

Revision ID: 816c073c1073
Revises: db3d7f0a7a89
Create Date: 2026-07-29 11:41:05.781397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816c073c1073'
down_revision: Union[str, None] = 'db3d7f0a7a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('entity', sa.String(length=20), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('fmt', sa.String(length=8), nullable=False),
    sa.Column('cadence', sa.String(length=12), nullable=False),
    sa.Column('driver', sa.String(length=12), nullable=False),
    sa.Column('recipients', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=240), server_default='', nullable=False),
    sa.Column('run_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'owner', 'name', name='uq_subscription_name')
    )
    op.create_index(op.f('ix_report_subscriptions_owner'), 'report_subscriptions', ['owner'], unique=False)
    op.create_index(op.f('ix_report_subscriptions_tenant_id'), 'report_subscriptions', ['tenant_id'], unique=False)
    op.create_index('ix_subscription_tenant_active', 'report_subscriptions', ['tenant_id', 'active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscription_tenant_active', table_name='report_subscriptions')
    op.drop_index(op.f('ix_report_subscriptions_tenant_id'), table_name='report_subscriptions')
    op.drop_index(op.f('ix_report_subscriptions_owner'), table_name='report_subscriptions')
    op.drop_table('report_subscriptions')
    # ### end Alembic commands ###
