"""ingestion raw transactions

Revision ID: 85e629e66d8e
Revises: f61e3cb63524
Create Date: 2026-07-30 16:40:28.001250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e629e66d8e'
down_revision: Union[str, None] = 'f61e3cb63524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The schema is the ingestion service's own; nothing else may write it.
    op.execute('CREATE SCHEMA IF NOT EXISTS "ingestion"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_transaction',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('rail', sa.String(length=8), nullable=False),
    sa.Column('source_txn_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('canonical', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('claim_token', sa.String(length=36), server_default='', nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.Column('source', sa.String(length=16), server_default='live', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'rail', 'source_txn_id', name='uq_raw_txn_source'),
    schema='ingestion'
    )
    op.create_index(op.f('ix_ingestion_raw_transaction_rail'), 'raw_transaction', ['rail'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_raw_transaction_received_at'), 'raw_transaction', ['received_at'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_raw_transaction_source_txn_id'), 'raw_transaction', ['source_txn_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_raw_transaction_state'), 'raw_transaction', ['state'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_raw_transaction_tenant_id'), 'raw_transaction', ['tenant_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_raw_transaction_ts'), 'raw_transaction', ['ts'], unique=False, schema='ingestion')
    op.create_index('ix_raw_txn_pending', 'raw_transaction', ['tenant_id', 'state', 'received_at'], unique=False, schema='ingestion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_txn_pending', table_name='raw_transaction', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_raw_transaction_ts'), table_name='raw_transaction', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_raw_transaction_tenant_id'), table_name='raw_transaction', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_raw_transaction_state'), table_name='raw_transaction', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_raw_transaction_source_txn_id'), table_name='raw_transaction', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_raw_transaction_received_at'), table_name='raw_transaction', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_raw_transaction_rail'), table_name='raw_transaction', schema='ingestion')
    op.drop_table('raw_transaction', schema='ingestion')
    # ### end Alembic commands ###
    op.execute('DROP SCHEMA IF EXISTS "ingestion" RESTRICT')
