"""fact provenance

Revision ID: 8ee0a7beb988
Revises: 85e629e66d8e
Create Date: 2026-07-30 16:41:05.726344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee0a7beb988'
down_revision: Union[str, None] = '85e629e66d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_alert', sa.Column('source', sa.String(length=16), server_default='synthetic', nullable=False), schema='analytics')
    op.create_index(op.f('ix_analytics_fact_alert_source'), 'fact_alert', ['source'], unique=False, schema='analytics')
    op.add_column('fact_transaction', sa.Column('source', sa.String(length=16), server_default='synthetic', nullable=False), schema='analytics')
    op.create_index(op.f('ix_analytics_fact_transaction_source'), 'fact_transaction', ['source'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_fact_transaction_source'), table_name='fact_transaction', schema='analytics')
    op.drop_column('fact_transaction', 'source', schema='analytics')
    op.drop_index(op.f('ix_analytics_fact_alert_source'), table_name='fact_alert', schema='analytics')
    op.drop_column('fact_alert', 'source', schema='analytics')
    # ### end Alembic commands ###
