"""mfa sessions and lockout

Revision ID: 8f5e44aba95b
Revises: 7d76cf9fab53
Create Date: 2026-08-02 15:40:49.828860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5e44aba95b'
down_revision: Union[str, None] = '7d76cf9fab53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_backup_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_kind', sa.String(length=10), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index('ix_backup_user', 'mfa_backup_codes', ['user_kind', 'user_id', 'used_at'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_mfa_backup_codes_code_hash'), 'mfa_backup_codes', ['code_hash'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_mfa_backup_codes_user_id'), 'mfa_backup_codes', ['user_id'], unique=False, schema='tenant')
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_kind', sa.String(length=10), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('refresh_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('rotated_from', sa.String(length=36), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=40), server_default='', nullable=False),
    sa.Column('user_agent', sa.String(length=255), server_default='', nullable=False),
    sa.Column('ip_addr', sa.String(length=45), server_default='', nullable=False),
    sa.Column('mfa_satisfied', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tenant'
    )
    op.create_index('ix_session_user', 'user_sessions', ['user_kind', 'user_id', 'revoked_at'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_user_sessions_family_id'), 'user_sessions', ['family_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_user_sessions_refresh_hash'), 'user_sessions', ['refresh_hash'], unique=True, schema='tenant')
    op.create_index(op.f('ix_tenant_user_sessions_subject'), 'user_sessions', ['subject'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_user_sessions_tenant_id'), 'user_sessions', ['tenant_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False, schema='tenant')
    op.add_column('platform_users', sa.Column('mfa_secret', sa.String(length=64), server_default='', nullable=False), schema='tenant')
    op.add_column('platform_users', sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False), schema='tenant')
    op.add_column('platform_users', sa.Column('mfa_enrolled_at', sa.DateTime(timezone=True), nullable=True), schema='tenant')
    op.add_column('platform_users', sa.Column('failed_attempts', sa.Integer(), server_default='0', nullable=False), schema='tenant')
    op.add_column('platform_users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True), schema='tenant')
    op.add_column('platform_users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True), schema='tenant')
    op.add_column('tenant_users', sa.Column('mfa_secret', sa.String(length=64), server_default='', nullable=False), schema='tenant')
    op.add_column('tenant_users', sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False), schema='tenant')
    op.add_column('tenant_users', sa.Column('mfa_enrolled_at', sa.DateTime(timezone=True), nullable=True), schema='tenant')
    op.add_column('tenant_users', sa.Column('failed_attempts', sa.Integer(), server_default='0', nullable=False), schema='tenant')
    op.add_column('tenant_users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True), schema='tenant')
    op.add_column('tenant_users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True), schema='tenant')
    op.add_column('tenants', sa.Column('mfa_policy', sa.String(length=16), server_default='privileged', nullable=False), schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'mfa_policy', schema='tenant')
    op.drop_column('tenant_users', 'last_login_at', schema='tenant')
    op.drop_column('tenant_users', 'locked_until', schema='tenant')
    op.drop_column('tenant_users', 'failed_attempts', schema='tenant')
    op.drop_column('tenant_users', 'mfa_enrolled_at', schema='tenant')
    op.drop_column('tenant_users', 'mfa_enabled', schema='tenant')
    op.drop_column('tenant_users', 'mfa_secret', schema='tenant')
    op.drop_column('platform_users', 'last_login_at', schema='tenant')
    op.drop_column('platform_users', 'locked_until', schema='tenant')
    op.drop_column('platform_users', 'failed_attempts', schema='tenant')
    op.drop_column('platform_users', 'mfa_enrolled_at', schema='tenant')
    op.drop_column('platform_users', 'mfa_enabled', schema='tenant')
    op.drop_column('platform_users', 'mfa_secret', schema='tenant')
    op.drop_index(op.f('ix_tenant_user_sessions_user_id'), table_name='user_sessions', schema='tenant')
    op.drop_index(op.f('ix_tenant_user_sessions_tenant_id'), table_name='user_sessions', schema='tenant')
    op.drop_index(op.f('ix_tenant_user_sessions_subject'), table_name='user_sessions', schema='tenant')
    op.drop_index(op.f('ix_tenant_user_sessions_refresh_hash'), table_name='user_sessions', schema='tenant')
    op.drop_index(op.f('ix_tenant_user_sessions_family_id'), table_name='user_sessions', schema='tenant')
    op.drop_index(op.f('ix_tenant_user_sessions_expires_at'), table_name='user_sessions', schema='tenant')
    op.drop_index('ix_session_user', table_name='user_sessions', schema='tenant')
    op.drop_table('user_sessions', schema='tenant')
    op.drop_index(op.f('ix_tenant_mfa_backup_codes_user_id'), table_name='mfa_backup_codes', schema='tenant')
    op.drop_index(op.f('ix_tenant_mfa_backup_codes_code_hash'), table_name='mfa_backup_codes', schema='tenant')
    op.drop_index('ix_backup_user', table_name='mfa_backup_codes', schema='tenant')
    op.drop_table('mfa_backup_codes', schema='tenant')
    # ### end Alembic commands ###
