"""ctr_filings (BR-508)

Revision ID: a7e2c9f14b83
Revises: d4a91c7e2f30
Create Date: 2026-08-14 16:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e2c9f14b83'
down_revision: Union[str, None] = 'd4a91c7e2f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ctr_filings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('account', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=14), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.String(length=255), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.String(length=255), nullable=False),
    sa.Column('reference_number', sa.String(length=120), nullable=False),
    sa.Column('ack_note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account', 'period', 'revision', name='uq_ctr_account_period_revision'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_ctr_filings_account'), 'ctr_filings', ['account'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_ctr_filings_content_hash'), 'ctr_filings', ['content_hash'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_ctr_filings_period'), 'ctr_filings', ['period'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_ctr_filings_status'), 'ctr_filings', ['status'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_ctr_filings_tenant_id'), 'ctr_filings', ['tenant_id'], unique=False, schema='analytics')
    op.create_index('ix_ctr_account_period', 'ctr_filings', ['tenant_id', 'account', 'period'], unique=False, schema='analytics')
    op.create_index('ix_ctr_status', 'ctr_filings', ['tenant_id', 'status'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ctr_status', table_name='ctr_filings', schema='analytics')
    op.drop_index('ix_ctr_account_period', table_name='ctr_filings', schema='analytics')
    op.drop_index(op.f('ix_analytics_ctr_filings_tenant_id'), table_name='ctr_filings', schema='analytics')
    op.drop_index(op.f('ix_analytics_ctr_filings_status'), table_name='ctr_filings', schema='analytics')
    op.drop_index(op.f('ix_analytics_ctr_filings_period'), table_name='ctr_filings', schema='analytics')
    op.drop_index(op.f('ix_analytics_ctr_filings_content_hash'), table_name='ctr_filings', schema='analytics')
    op.drop_index(op.f('ix_analytics_ctr_filings_account'), table_name='ctr_filings', schema='analytics')
    op.drop_table('ctr_filings', schema='analytics')
    # ### end Alembic commands ###
