"""analytical fact tables

Revision ID: b47b389d805e
Revises: f7d2d9a5d6ca
Create Date: 2026-07-28 12:42:38.666274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b47b389d805e'
down_revision: Union[str, None] = 'f7d2d9a5d6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_alert',
    sa.Column('alert_id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('txn_id', sa.String(length=40), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rule_family', sa.String(length=8), nullable=False),
    sa.Column('rule_id', sa.String(length=24), nullable=False),
    sa.Column('typology', sa.String(length=48), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('disposition', sa.String(length=16), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('analyst', sa.String(length=64), nullable=False),
    sa.Column('first_touch_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disposition_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_version', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('ix_alert_tenant_ts', 'fact_alert', ['tenant_id', 'ts'], unique=False)
    op.create_index(op.f('ix_fact_alert_case_id'), 'fact_alert', ['case_id'], unique=False)
    op.create_index(op.f('ix_fact_alert_disposition'), 'fact_alert', ['disposition'], unique=False)
    op.create_index(op.f('ix_fact_alert_rule_family'), 'fact_alert', ['rule_family'], unique=False)
    op.create_index(op.f('ix_fact_alert_rule_id'), 'fact_alert', ['rule_id'], unique=False)
    op.create_index(op.f('ix_fact_alert_severity'), 'fact_alert', ['severity'], unique=False)
    op.create_index(op.f('ix_fact_alert_tenant_id'), 'fact_alert', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_fact_alert_ts'), 'fact_alert', ['ts'], unique=False)
    op.create_index(op.f('ix_fact_alert_txn_id'), 'fact_alert', ['txn_id'], unique=False)
    op.create_table('fact_case',
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('opened_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('fmr_category', sa.String(length=40), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('recovered_paise', sa.BigInteger(), nullable=False),
    sa.Column('rfa_flag', sa.Boolean(), nullable=False),
    sa.Column('rail', sa.String(length=8), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('product', sa.String(length=20), nullable=False),
    sa.Column('customer_segment', sa.String(length=12), nullable=False),
    sa.Column('assignee', sa.String(length=64), nullable=False),
    sa.Column('show_cause_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_due_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fmr_due_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fmr_filed_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('str_due_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('str_filed_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_ts', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index('ix_case_tenant_opened', 'fact_case', ['tenant_id', 'opened_ts'], unique=False)
    op.create_index(op.f('ix_fact_case_customer_segment'), 'fact_case', ['customer_segment'], unique=False)
    op.create_index(op.f('ix_fact_case_fmr_category'), 'fact_case', ['fmr_category'], unique=False)
    op.create_index(op.f('ix_fact_case_opened_ts'), 'fact_case', ['opened_ts'], unique=False)
    op.create_index(op.f('ix_fact_case_product'), 'fact_case', ['product'], unique=False)
    op.create_index(op.f('ix_fact_case_rail'), 'fact_case', ['rail'], unique=False)
    op.create_index(op.f('ix_fact_case_region'), 'fact_case', ['region'], unique=False)
    op.create_index(op.f('ix_fact_case_severity'), 'fact_case', ['severity'], unique=False)
    op.create_index(op.f('ix_fact_case_state'), 'fact_case', ['state'], unique=False)
    op.create_index(op.f('ix_fact_case_tenant_id'), 'fact_case', ['tenant_id'], unique=False)
    op.create_table('fact_transaction',
    sa.Column('txn_id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rail', sa.String(length=8), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('debtor_account', sa.String(length=32), nullable=False),
    sa.Column('creditor_account', sa.String(length=32), nullable=False),
    sa.Column('branch', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('product', sa.String(length=20), nullable=False),
    sa.Column('customer_segment', sa.String(length=12), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('ip_addr', sa.String(length=45), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('txn_id')
    )
    op.create_index(op.f('ix_fact_transaction_creditor_account'), 'fact_transaction', ['creditor_account'], unique=False)
    op.create_index(op.f('ix_fact_transaction_customer_segment'), 'fact_transaction', ['customer_segment'], unique=False)
    op.create_index(op.f('ix_fact_transaction_debtor_account'), 'fact_transaction', ['debtor_account'], unique=False)
    op.create_index(op.f('ix_fact_transaction_product'), 'fact_transaction', ['product'], unique=False)
    op.create_index(op.f('ix_fact_transaction_rail'), 'fact_transaction', ['rail'], unique=False)
    op.create_index(op.f('ix_fact_transaction_region'), 'fact_transaction', ['region'], unique=False)
    op.create_index(op.f('ix_fact_transaction_tenant_id'), 'fact_transaction', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_fact_transaction_ts'), 'fact_transaction', ['ts'], unique=False)
    op.create_index('ix_txn_tenant_ts', 'fact_transaction', ['tenant_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_txn_tenant_ts', table_name='fact_transaction')
    op.drop_index(op.f('ix_fact_transaction_ts'), table_name='fact_transaction')
    op.drop_index(op.f('ix_fact_transaction_tenant_id'), table_name='fact_transaction')
    op.drop_index(op.f('ix_fact_transaction_region'), table_name='fact_transaction')
    op.drop_index(op.f('ix_fact_transaction_rail'), table_name='fact_transaction')
    op.drop_index(op.f('ix_fact_transaction_product'), table_name='fact_transaction')
    op.drop_index(op.f('ix_fact_transaction_debtor_account'), table_name='fact_transaction')
    op.drop_index(op.f('ix_fact_transaction_customer_segment'), table_name='fact_transaction')
    op.drop_index(op.f('ix_fact_transaction_creditor_account'), table_name='fact_transaction')
    op.drop_table('fact_transaction')
    op.drop_index(op.f('ix_fact_case_tenant_id'), table_name='fact_case')
    op.drop_index(op.f('ix_fact_case_state'), table_name='fact_case')
    op.drop_index(op.f('ix_fact_case_severity'), table_name='fact_case')
    op.drop_index(op.f('ix_fact_case_region'), table_name='fact_case')
    op.drop_index(op.f('ix_fact_case_rail'), table_name='fact_case')
    op.drop_index(op.f('ix_fact_case_product'), table_name='fact_case')
    op.drop_index(op.f('ix_fact_case_opened_ts'), table_name='fact_case')
    op.drop_index(op.f('ix_fact_case_fmr_category'), table_name='fact_case')
    op.drop_index(op.f('ix_fact_case_customer_segment'), table_name='fact_case')
    op.drop_index('ix_case_tenant_opened', table_name='fact_case')
    op.drop_table('fact_case')
    op.drop_index(op.f('ix_fact_alert_txn_id'), table_name='fact_alert')
    op.drop_index(op.f('ix_fact_alert_ts'), table_name='fact_alert')
    op.drop_index(op.f('ix_fact_alert_tenant_id'), table_name='fact_alert')
    op.drop_index(op.f('ix_fact_alert_severity'), table_name='fact_alert')
    op.drop_index(op.f('ix_fact_alert_rule_id'), table_name='fact_alert')
    op.drop_index(op.f('ix_fact_alert_rule_family'), table_name='fact_alert')
    op.drop_index(op.f('ix_fact_alert_disposition'), table_name='fact_alert')
    op.drop_index(op.f('ix_fact_alert_case_id'), table_name='fact_alert')
    op.drop_index('ix_alert_tenant_ts', table_name='fact_alert')
    op.drop_table('fact_alert')
    # ### end Alembic commands ###
