"""SAML 2.0 provider fields and assertion replay cache

Revision ID: b68531fc8d4e
Revises: bc10243ec143
Create Date: 2026-08-03 20:33:34.855862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68531fc8d4e'
down_revision: Union[str, None] = 'bc10243ec143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saml_assertions_seen',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('assertion_id', sa.String(length=255), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'assertion_id', name='uq_saml_assertion'),
    schema='tenant'
    )
    op.create_index('ix_saml_assertion_expiry', 'saml_assertions_seen', ['expires_at'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_saml_assertions_seen_provider_id'), 'saml_assertions_seen', ['provider_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_saml_assertions_seen_tenant_id'), 'saml_assertions_seen', ['tenant_id'], unique=False, schema='tenant')
    op.add_column('identity_providers', sa.Column('saml_sso_url', sa.String(length=500), server_default='', nullable=False), schema='tenant')
    op.add_column('identity_providers', sa.Column('saml_certificate', sa.Text(), server_default='', nullable=False), schema='tenant')
    op.add_column('identity_providers', sa.Column('saml_email_attribute', sa.String(length=255), server_default='', nullable=False), schema='tenant')
    op.add_column('identity_providers', sa.Column('saml_groups_attribute', sa.String(length=255), server_default='', nullable=False), schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity_providers', 'saml_groups_attribute', schema='tenant')
    op.drop_column('identity_providers', 'saml_email_attribute', schema='tenant')
    op.drop_column('identity_providers', 'saml_certificate', schema='tenant')
    op.drop_column('identity_providers', 'saml_sso_url', schema='tenant')
    op.drop_index(op.f('ix_tenant_saml_assertions_seen_tenant_id'), table_name='saml_assertions_seen', schema='tenant')
    op.drop_index(op.f('ix_tenant_saml_assertions_seen_provider_id'), table_name='saml_assertions_seen', schema='tenant')
    op.drop_index('ix_saml_assertion_expiry', table_name='saml_assertions_seen', schema='tenant')
    op.drop_table('saml_assertions_seen', schema='tenant')
    # ### end Alembic commands ###
