"""case transition log

Revision ID: bb78d861c557
Revises: 14a6e56ff686
Create Date: 2026-07-29 15:07:46.676011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb78d861c557'
down_revision: Union[str, None] = '14a6e56ff686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_transitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('from_state', sa.String(length=24), nullable=False),
    sa.Column('to_state', sa.String(length=24), server_default='', nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('refusal_code', sa.String(length=32), server_default='', nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('breached_policy', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('breach_days_allowed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('approves_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_transition_case', 'case_transitions', ['tenant_id', 'case_id', 'created_at'], unique=False)
    op.create_index('ix_case_transition_pending', 'case_transitions', ['tenant_id', 'case_id', 'status'], unique=False)
    op.create_index(op.f('ix_case_transitions_actor'), 'case_transitions', ['actor'], unique=False)
    op.create_index(op.f('ix_case_transitions_case_id'), 'case_transitions', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_transitions_created_at'), 'case_transitions', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_transitions_status'), 'case_transitions', ['status'], unique=False)
    op.create_index(op.f('ix_case_transitions_tenant_id'), 'case_transitions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_transitions_tenant_id'), table_name='case_transitions')
    op.drop_index(op.f('ix_case_transitions_status'), table_name='case_transitions')
    op.drop_index(op.f('ix_case_transitions_created_at'), table_name='case_transitions')
    op.drop_index(op.f('ix_case_transitions_case_id'), table_name='case_transitions')
    op.drop_index(op.f('ix_case_transitions_actor'), table_name='case_transitions')
    op.drop_index('ix_case_transition_pending', table_name='case_transitions')
    op.drop_index('ix_case_transition_case', table_name='case_transitions')
    op.drop_table('case_transitions')
    # ### end Alembic commands ###
