"""batch file intake and quarantine

Revision ID: bc10243ec143
Revises: 4170c1d10273
Create Date: 2026-08-03 14:41:54.529425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc10243ec143'
down_revision: Union[str, None] = '4170c1d10273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('rail', sa.String(length=8), server_default='', nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_accepted', sa.Integer(), nullable=False),
    sa.Column('rows_duplicate', sa.Integer(), nullable=False),
    sa.Column('rows_quarantined', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.Column('archived_path', sa.String(length=600), server_default='', nullable=False),
    sa.Column('duplicate_of', sa.String(length=36), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='file', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sha256', name='uq_ingest_file_digest'),
    schema='ingestion'
    )
    op.create_index('ix_ingest_file_tenant_state', 'ingest_files', ['tenant_id', 'state', 'received_at'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_ingest_files_received_at'), 'ingest_files', ['received_at'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_ingest_files_sha256'), 'ingest_files', ['sha256'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_ingest_files_state'), 'ingest_files', ['state'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_ingest_files_tenant_id'), 'ingest_files', ['tenant_id'], unique=False, schema='ingestion')
    op.create_table('quarantined_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion'
    )
    op.create_index(op.f('ix_ingestion_quarantined_rows_file_id'), 'quarantined_rows', ['file_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_quarantined_rows_tenant_id'), 'quarantined_rows', ['tenant_id'], unique=False, schema='ingestion')
    op.create_index('ix_quarantine_file', 'quarantined_rows', ['tenant_id', 'file_id'], unique=False, schema='ingestion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quarantine_file', table_name='quarantined_rows', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_quarantined_rows_tenant_id'), table_name='quarantined_rows', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_quarantined_rows_file_id'), table_name='quarantined_rows', schema='ingestion')
    op.drop_table('quarantined_rows', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_ingest_files_tenant_id'), table_name='ingest_files', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_ingest_files_state'), table_name='ingest_files', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_ingest_files_sha256'), table_name='ingest_files', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_ingest_files_received_at'), table_name='ingest_files', schema='ingestion')
    op.drop_index('ix_ingest_file_tenant_state', table_name='ingest_files', schema='ingestion')
    op.drop_table('ingest_files', schema='ingestion')
    # ### end Alembic commands ###
