"""board and ACB pack (BR-507)

Revision ID: c986942e0dc4
Revises: 3846bf1545f3
Create Date: 2026-08-03 13:10:30.218579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c986942e0dc4'
down_revision: Union[str, None] = '3846bf1545f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_pack_distributions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('pack_id', sa.String(length=36), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=60), server_default='', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_id', 'recipient', name='uq_pack_recipient'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_board_pack_distributions_pack_id'), 'board_pack_distributions', ['pack_id'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_board_pack_distributions_tenant_id'), 'board_pack_distributions', ['tenant_id'], unique=False, schema='analytics')
    op.create_index('ix_pack_dist_tenant', 'board_pack_distributions', ['tenant_id', 'pack_id'], unique=False, schema='analytics')
    op.create_table('board_packs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('period_label', sa.String(length=60), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cadence', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_by', sa.String(length=255), server_default='', nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_board_packs_period_start'), 'board_packs', ['period_start'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_board_packs_status'), 'board_packs', ['status'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_board_packs_tenant_id'), 'board_packs', ['tenant_id'], unique=False, schema='analytics')
    op.create_index('ix_board_pack_tenant_period', 'board_packs', ['tenant_id', 'period_start'], unique=False, schema='analytics')
    op.create_index('ix_board_pack_tenant_status', 'board_packs', ['tenant_id', 'status'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_board_pack_tenant_status', table_name='board_packs', schema='analytics')
    op.drop_index('ix_board_pack_tenant_period', table_name='board_packs', schema='analytics')
    op.drop_index(op.f('ix_analytics_board_packs_tenant_id'), table_name='board_packs', schema='analytics')
    op.drop_index(op.f('ix_analytics_board_packs_status'), table_name='board_packs', schema='analytics')
    op.drop_index(op.f('ix_analytics_board_packs_period_start'), table_name='board_packs', schema='analytics')
    op.drop_table('board_packs', schema='analytics')
    op.drop_index('ix_pack_dist_tenant', table_name='board_pack_distributions', schema='analytics')
    op.drop_index(op.f('ix_analytics_board_pack_distributions_tenant_id'), table_name='board_pack_distributions', schema='analytics')
    op.drop_index(op.f('ix_analytics_board_pack_distributions_pack_id'), table_name='board_pack_distributions', schema='analytics')
    op.drop_table('board_pack_distributions', schema='analytics')
    # ### end Alembic commands ###
