"""CBS and loan-conduct events (BR-211)

Revision ID: ca624b9a4a07
Revises: 6e1d47d7644b
Create Date: 2026-08-04 07:28:51.283049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca624b9a4a07'
down_revision: Union[str, None] = '6e1d47d7644b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cbs_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('source_event_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account', sa.String(length=40), nullable=False),
    sa.Column('counterparty_account', sa.String(length=40), server_default='', nullable=False),
    sa.Column('counterparty_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('funding_source', sa.String(length=24), server_default='', nullable=False),
    sa.Column('routed_through_lender', sa.Boolean(), nullable=True),
    sa.Column('within_sanctioned_purpose', sa.Boolean(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.Column('source', sa.String(length=16), server_default='cbs', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_event_id', name='uq_cbs_event_source'),
    schema='ingestion'
    )
    op.create_index('ix_cbs_event_account', 'cbs_events', ['tenant_id', 'account', 'ts'], unique=False, schema='ingestion')
    op.create_index('ix_cbs_event_pending', 'cbs_events', ['tenant_id', 'state', 'received_at'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_cbs_events_account'), 'cbs_events', ['account'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_cbs_events_kind'), 'cbs_events', ['kind'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_cbs_events_received_at'), 'cbs_events', ['received_at'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_cbs_events_source_event_id'), 'cbs_events', ['source_event_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_cbs_events_state'), 'cbs_events', ['state'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_cbs_events_tenant_id'), 'cbs_events', ['tenant_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_cbs_events_ts'), 'cbs_events', ['ts'], unique=False, schema='ingestion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_cbs_events_ts'), table_name='cbs_events', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_cbs_events_tenant_id'), table_name='cbs_events', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_cbs_events_state'), table_name='cbs_events', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_cbs_events_source_event_id'), table_name='cbs_events', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_cbs_events_received_at'), table_name='cbs_events', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_cbs_events_kind'), table_name='cbs_events', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_cbs_events_account'), table_name='cbs_events', schema='ingestion')
    op.drop_index('ix_cbs_event_pending', table_name='cbs_events', schema='ingestion')
    op.drop_index('ix_cbs_event_account', table_name='cbs_events', schema='ingestion')
    op.drop_table('cbs_events', schema='ingestion')
    # ### end Alembic commands ###
