"""config activation maker-checker (BR-715)

Revision ID: d4a91c7e2f30
Revises: 293f67391b64
Create Date: 2026-08-14 15:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a91c7e2f30'
down_revision: Union[str, None] = '293f67391b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_configs', 'status',
        existing_type=sa.String(length=16),
        type_=sa.String(length=20),
        existing_nullable=False,
        schema='config')
    op.add_column('tenant_configs', sa.Column('proposed_by', sa.String(length=128), nullable=True), schema='config')
    op.add_column('tenant_configs', sa.Column('proposed_by_role', sa.String(length=32), nullable=True), schema='config')
    op.add_column('tenant_configs', sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=True), schema='config')
    op.add_column('tenant_configs', sa.Column('approved_by', sa.String(length=128), nullable=True), schema='config')
    op.add_column('tenant_configs', sa.Column('approved_by_role', sa.String(length=32), nullable=True), schema='config')
    op.add_column('tenant_configs', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True), schema='config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_configs', 'approved_at', schema='config')
    op.drop_column('tenant_configs', 'approved_by_role', schema='config')
    op.drop_column('tenant_configs', 'approved_by', schema='config')
    op.drop_column('tenant_configs', 'proposed_at', schema='config')
    op.drop_column('tenant_configs', 'proposed_by_role', schema='config')
    op.drop_column('tenant_configs', 'proposed_by', schema='config')
    op.alter_column('tenant_configs', 'status',
        existing_type=sa.String(length=20),
        type_=sa.String(length=16),
        existing_nullable=False,
        schema='config')
    # ### end Alembic commands ###
