"""case documents

Revision ID: db3d7f0a7a89
Revises: 4d2eb9625d28
Create Date: 2026-07-29 11:32:08.584244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3d7f0a7a89'
down_revision: Union[str, None] = '4d2eb9625d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=500), server_default='', nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_doc_tenant_case', 'case_documents', ['tenant_id', 'case_id'], unique=False)
    op.create_index(op.f('ix_case_documents_case_id'), 'case_documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_documents_doc_type'), 'case_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_case_documents_tenant_id'), 'case_documents', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_documents_tenant_id'), table_name='case_documents')
    op.drop_index(op.f('ix_case_documents_doc_type'), table_name='case_documents')
    op.drop_index(op.f('ix_case_documents_case_id'), table_name='case_documents')
    op.drop_index('ix_case_doc_tenant_case', table_name='case_documents')
    op.drop_table('case_documents')
    # ### end Alembic commands ###
