"""idempotency keys

Revision ID: f61e3cb63524
Revises: 1af497e9e69a
Create Date: 2026-07-30 15:57:04.711665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61e3cb63524'
down_revision: Union[str, None] = '1af497e9e69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=True),
    sa.Column('body_stored', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'key'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False, schema='platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_idempotency_keys_expires_at'), table_name='idempotency_keys', schema='platform')
    op.drop_table('idempotency_keys', schema='platform')
    # ### end Alembic commands ###
