"""tenant entity type and FRM policy

Revision ID: f7e764173845
Revises: b5138fae8647
Create Date: 2026-07-29 10:06:06.810231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e764173845'
down_revision: Union[str, None] = 'b5138fae8647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('entity_type', sa.String(length=24), server_default='commercial_bank', nullable=False))
    op.add_column('tenants', sa.Column('ucb_tier', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'ucb_tier')
    op.drop_column('tenants', 'entity_type')
    # ### end Alembic commands ###
