"""BACKUP - not imported by the application.

A frozen, verbatim copy of packages/cp_common/cp_common/rbac.py as it stood on
2026-08-16, immediately before BR-113 began materialising this hardcoded catalogue
into a per-tenant `tenant_roles` table (see services/tenant_service/app/roles.py).

Why this exists: rbac.py remains the single source of truth for authorisation -
every `require_role()` check still resolves against it, unchanged, after BR-113's
first slice. This snapshot is the rollback point and the equivalence baseline: BR-113's
seeding logic is tested against exactly this file's ROLES dict (see
tests/test_role_seeding.py::test_seeded_rows_match_the_backed_up_hardcoded_catalogue),
so a future edit to the live rbac.py that silently drifts from what tenants were
actually seeded with is something a test catches, not something discovered in
production. Restore by copying this file's content back over rbac.py if a BR-113
change needs to be rolled back.

Do not edit this file. If the live catalogue changes, cut a new dated snapshot instead.
"""
from dataclasses import dataclass

# ---- modules ----
MOD_CONTROL_PLANE = "control_plane"   # tenants, branding, users, detection configs
MOD_MONITORING = "monitoring"         # FRMS/EWS dashboards
MOD_AUDIT = "audit"                   # activity trail
MOD_ADMIN = "administration"          # platform-wide administration

ALL_MODULES = [MOD_CONTROL_PLANE, MOD_MONITORING, MOD_AUDIT, MOD_ADMIN]

MODULE_META = {
    MOD_CONTROL_PLANE: {"label": "Control Plane", "icon": "◧",
                        "description": "Tenants, branding, users and detection configuration"},
    MOD_MONITORING: {"label": "Monitoring", "icon": "◕",
                     "description": "FRMS and EWS dashboards with drill-down"},
    MOD_AUDIT: {"label": "Audit", "icon": "◔",
                "description": "Activity trail and evidence"},
    MOD_ADMIN: {"label": "Administration", "icon": "◆",
                "description": "Platform-wide administration"},
}

# ---- dashboards (within the monitoring module) ----
DASHBOARDS = [
    # Ordered by the spec's delivery priority: P1 first, then P2, then P3.
    "analyst", "ews", "rfa", "board", "supervisor",          # P1
    "realtime", "aml", "account360",                          # P2
    "investigator", "model", "tenant_health",                 # P3
    "risk_manager", "inspection",                             # beyond the original catalogue
]
DASHBOARD_META = {
    "analyst":      {"label": "Analyst",      "persona": "L1 Fraud Analyst",
                     "question": "What do I work next, and is it real?"},
    "investigator": {"label": "Investigator", "persona": "L2 Senior Investigator",
                     "question": "Is this one mule, or a ring?"},
    "risk_manager": {"label": "Operations",   "persona": "Fraud Risk Manager",
                     "question": "Where is the queue failing, and why?"},
    "aml":          {"label": "AML / STR",    "persona": "Principal Officer (PMLA)",
                     "question": "What must be filed with FIU-IND, by when?"},
    "board":        {"label": "Board",        "persona": "CRO / ACB / Special Committee",
                     "question": "What is our exposure and are we compliant?"},
    "supervisor":   {"label": "Compliance",   "persona": "Compliance Supervisor",
                     "question": "Are the regulatory clocks being met?"},
    "model":        {"label": "Model Risk",   "persona": "Model Risk / Data Science",
                     "question": "Is the model still fit, fair and explainable?"},
    "inspection":   {"label": "Inspection",   "persona": "Internal Audit / RBI Inspection",
                     "question": "Prove why this account was flagged."},
    "ews":          {"label": "EWS Signals",  "persona": "Fraud Risk Manager / Analyst",
                     "question": "Which indicators are firing - and which are silent?"},
    "rfa":          {"label": "RFA Lifecycle","persona": "Investigator / Compliance",
                     "question": "Where is each red-flagged account in its lifecycle?"},
    "realtime":     {"label": "Real-Time",    "persona": "Operations",
                     "question": "What is flowing right now, and what are we stopping?"},
    "account360":   {"label": "Account 360",  "persona": "Investigator",
                     "question": "Everything known about one account."},
    "tenant_health":{"label": "Tenant Health","persona": "Platform Administrator",
                     "question": "Which bank's pipeline is degraded?"},
}


@dataclass(frozen=True)
class Role:
    name: str
    label: str
    modules: tuple[str, ...]
    dashboards: tuple[str, ...]
    tenant_scoped: bool      # False = may act across tenants
    can_admin_tenant: bool   # may change branding/users/configs for its tenant
    can_reveal_pii: bool = False


_ALL_DASH = tuple(DASHBOARDS)
_TENANT_DASH = tuple(d for d in DASHBOARDS if d != "tenant_health")

ROLES: dict[str, Role] = {
    "platform_admin": Role(
        "platform_admin", "Platform Administrator",
        (MOD_CONTROL_PLANE, MOD_MONITORING, MOD_AUDIT, MOD_ADMIN),
        _ALL_DASH, tenant_scoped=False, can_admin_tenant=True, can_reveal_pii=False),

    "tenant_admin": Role(
        "tenant_admin", "Tenant Administrator",
        (MOD_CONTROL_PLANE, MOD_MONITORING, MOD_AUDIT),
        _TENANT_DASH, tenant_scoped=True, can_admin_tenant=True, can_reveal_pii=True),

    "analyst": Role(
        "analyst", "Fraud Analyst (L1)", (MOD_MONITORING,),
        ("analyst", "ews", "realtime"),
        tenant_scoped=True, can_admin_tenant=False, can_reveal_pii=True),

    "investigator": Role(
        "investigator", "Senior Investigator (L2)", (MOD_MONITORING,),
        ("investigator", "account360", "rfa", "ews", "analyst"),
        tenant_scoped=True, can_admin_tenant=False, can_reveal_pii=True),

    "risk_manager": Role(
        "risk_manager", "Fraud Risk Manager", (MOD_MONITORING, MOD_AUDIT),
        ("risk_manager", "ews", "realtime", "analyst", "investigator", "rfa", "board"),
        tenant_scoped=True, can_admin_tenant=False, can_reveal_pii=True),

    "principal_officer": Role(
        "principal_officer", "Principal Officer (PMLA)", (MOD_MONITORING, MOD_AUDIT),
        ("aml", "rfa", "supervisor"),
        tenant_scoped=True, can_admin_tenant=False, can_reveal_pii=True),

    "supervisor": Role(
        "supervisor", "Compliance Supervisor", (MOD_MONITORING, MOD_AUDIT),
        ("supervisor", "rfa", "aml", "ews", "board"),
        tenant_scoped=True, can_admin_tenant=False, can_reveal_pii=True),

    "board": Role(
        "board", "Board / Executive", (MOD_MONITORING,),
        ("board",), tenant_scoped=True, can_admin_tenant=False, can_reveal_pii=False),

    "cro": Role(
        "cro", "CRO / ACB / Special Committee", (MOD_MONITORING, MOD_AUDIT),
        ("board", "supervisor", "rfa", "risk_manager", "aml", "ews"),
        tenant_scoped=True, can_admin_tenant=False, can_reveal_pii=False),

    "data_scientist": Role(
        "data_scientist", "Model Risk / Data Science", (MOD_MONITORING,),
        ("model", "ews", "analyst"),
        tenant_scoped=True, can_admin_tenant=False, can_reveal_pii=False),

    "rbi_inspector": Role(
        "rbi_inspector", "Internal Audit / RBI Inspection",
        (MOD_MONITORING, MOD_AUDIT),
        ("inspection", "rfa", "supervisor", "board", "aml", "model", "ews", "account360"),
        tenant_scoped=True, can_admin_tenant=False, can_reveal_pii=True),
}

ASSIGNABLE_TENANT_ROLES = [
    "tenant_admin", "analyst", "investigator", "risk_manager",
    "principal_officer", "supervisor", "board", "cro",
    "data_scientist", "rbi_inspector",
]


def get_role(name: str) -> Role:
    return ROLES.get(name) or ROLES["analyst"]


def modules_for(role_name: str) -> list[dict]:
    role = get_role(role_name)
    return [{"key": m, **MODULE_META[m]} for m in role.modules]


def dashboards_for(role_name: str) -> list[dict]:
    role = get_role(role_name)
    return [{"key": d, **DASHBOARD_META[d]} for d in role.dashboards]


def can_access_module(role_name: str, module: str) -> bool:
    return module in get_role(role_name).modules


def can_access_dashboard(role_name: str, dashboard: str) -> bool:
    return dashboard in get_role(role_name).dashboards


def can_admin_tenant(role_name: str) -> bool:
    return get_role(role_name).can_admin_tenant


def can_reveal_pii(role_name: str) -> bool:
    return get_role(role_name).can_reveal_pii
