import { useState } from "react"

import { useSession } from "@/app/SessionContext"
import { ApiError } from "@/api/client"
import { generateAiInsights, type AiInsightsOut, type EvidenceEntity } from "@/api/evidence"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { StatCell } from "@/components/ui/sidebar"
import { DecisionBadge } from "./SeverityBadge"

// A real LLM's read of this record's evidence, generated on demand - see
// ai_insights.py. The model is a locally self-hosted open-source model (Ollama/vLLM),
// never a paid hosted API, so this only works when that model host is actually running;
// a clear "unavailable" state (not a fabricated result) is the honest failure mode.
export function AiInsightsPanel({
  tenantId,
  entity,
  ident,
  revealed,
  justification,
}: {
  tenantId: string
  entity: EvidenceEntity
  ident: string
  revealed: boolean
  justification?: string
}) {
  const { accessToken } = useSession()
  const [busy, setBusy] = useState(false)
  const [data, setData] = useState<AiInsightsOut | null>(null)
  const [error, setError] = useState<string | null>(null)

  function handleGenerate() {
    setBusy(true)
    setError(null)
    generateAiInsights(tenantId, entity, ident, { reveal: revealed, justification }, accessToken)
      .then(setData)
      .catch((err) => {
        if (err instanceof ApiError && err.code === "llm_unavailable") {
          setError(
            "The AI Insights model isn't reachable right now. It runs on a local model host " +
              "(Ollama/vLLM) rather than a paid cloud API - check that it's running and try again."
          )
        } else if (err instanceof ApiError) {
          setError(err.message)
        } else {
          setError("Could not generate AI Insights.")
        }
      })
      .finally(() => setBusy(false))
  }

  if (!data) {
    return (
      <div className="flex flex-col items-center gap-3 rounded-lg border border-dashed border-border py-10 text-center">
        <p className="max-w-sm text-sm text-muted-foreground">
          Generate an AI read of this record's evidence. Runs a real local model against exactly the
          data shown in this drawer - it can take a few seconds.
        </p>
        <Button onClick={handleGenerate} disabled={busy}>
          {busy ? "Generating…" : "Generate AI Insights"}
        </Button>
        {error && (
          <Alert variant="destructive" className="mt-2 max-w-sm text-left">
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}
      </div>
    )
  }

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-3 gap-3">
        <Card className="py-3"><CardContent className="px-4"><StatCell label="AI Decision" value={<DecisionBadge value={data.decision} />} /></CardContent></Card>
        <Card className="py-3"><CardContent className="px-4"><StatCell label="AI Risk Score" value={`${data.risk_score} / 100`} tone={data.risk_score >= 70 ? "warning" : "default"} /></CardContent></Card>
        <Card className="py-3"><CardContent className="px-4"><StatCell label="Model Confidence" value={`${data.confidence}%`} /></CardContent></Card>
      </div>

      <div className="space-y-1.5">
        <h6 className="text-xs font-medium tracking-wide text-muted-foreground uppercase">AI Narrative</h6>
        <p className="text-sm">{data.narrative}</p>
      </div>

      <div className="space-y-1.5">
        <h6 className="text-xs font-medium tracking-wide text-muted-foreground uppercase">Recommendations</h6>
        <ul className="list-inside list-disc space-y-1 text-sm">
          {data.recommendations.map((r, i) => <li key={i}>{r}</li>)}
        </ul>
      </div>

      <div className="flex flex-wrap items-center justify-between gap-2 border-t border-border pt-2">
        <p className="text-xs text-muted-foreground">
          Generated by <span className="font-mono">{data.model}</span>, a locally self-hosted open-source
          model — advisory only, not a substitute for analyst judgment or a compliance decision.
        </p>
        <Button size="sm" variant="ghost" onClick={handleGenerate} disabled={busy}>
          {busy ? "Regenerating…" : "Regenerate"}
        </Button>
      </div>
    </div>
  )
}
